config/routes.rb
Rails.application.routes.draw do

resources :users

resources :students

resources :courses



  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks",
                                                              :registrations => 'users/registrations'

                                                            }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :courses
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @students = Student.all
    render json: @students
  end

  def show
    @student = Student.find(params[:id])
    render json: @student
  end

  def create
    @student = Student.create!(student_params)
    render json: @student
  end

  def update
    @student = Student.find(params[:id])
    @student.update!(student_params)
    render json: @student
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    render nothing:true
  end



  private
  def student_params
    params.require(:student).permit(:full_name, :headline, :location, :position_title, :position_company, :picture_url, :profile_url, :mentor, :user_type, :user_skills, :email, :course)
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/index.html.erb
<% @students.each do |student| %>
<%= link_to student.full_name,  student_path(student) %>
<% end %>

app/views/students/show.html.erb
<li>Hello, <%= @student.email %></li>
<li>Hello, <%= @student.full_name %></li>
<li>Hello, <%= @student.headline %></li>
<li>Hello, <%= @student.location %></li>
<li>Hello, <%= @student.position_title %></li>
<li>Hello, <%= @student.position_company %></li>
<li>Hello, <%= @student.picture_url %></li>
<li>Hello, <%= @student.profile_url %></li>